In [1]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel('Food_Delivery.xlsx')

In [4]:
df.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    object
 2   Marital Status              388 non-null    object
 3   Occupation                  388 non-null    object
 4   Monthly Income              388 non-null    object
 5   Educational Qualifications  388 non-null    object
 6   Family size                 388 non-null    int64
 7   Customer Type               388 non-null    object
 8   latitude                    388 non-null    float64
 9   longitude                   388 non-null    float64
 10  Pin code                    388 non-null    int64
 11  Output                      388 non-null    object
 12  Feedback                    388 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 39.5+ KB

In [6]:
df.describe()

              Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

In [7]:
df.isnull().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
Customer Type                 0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(103)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.replace(['N/A','NULL',''],np.nan,inplace=True)

In [12]:
df

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive
374,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive

In [13]:
df=df.apply(lambda x:x.str.strip() if x.dtype=='object' else x)

In [14]:
df

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive
374,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive

In [15]:
df=df[df['Age']>16]

In [16]:
df=df[df['Family size']>0]

In [17]:
df = df.copy()

In [18]:
df['Output']=df['Output'].fillna('Yes')

In [19]:
df

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive
374,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive

In [20]:
df['Age_Group'] = pd.cut(df['Age'],bins=[0, 25, 35, 50, 100],labels=['18-25', '26-35', '36-50', '50+'])

In [21]:
df['Family_Size_Group'] = pd.cut(
    df['Family size'],
    bins=[0, 2, 4, float('inf')],
    labels=['Small', 'Medium', 'Large']
)

In [22]:
df['Feedback_Flag'] = df['Feedback'].map({
    'Positive': 1,
    'Negative': 0
})

In [23]:
df['Output_Flag'] = df['Output'].map({
    'Yes': 1,
    'No': 0
})

In [24]:
education_map = {
    'School': 1,
    'Graduate': 2,
    'Post Graduate': 3,
    'Ph.D': 4
}

df['Education_Level'] = df['Educational Qualifications'].map(education_map)

In [25]:
df

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Age_Group,Family_Size_Group,Feedback_Flag,Output_Flag,Education_Level
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,18-25,Medium,1,1,3.0
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,18-25,Medium,1,1,2.0
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,18-25,Medium,0,1,3.0
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,18-25,Large,1,1,2.0
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,18-25,Medium,1,1,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive,18-25,Small,1,0,2.0
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive,26-35,Medium,1,1,4.0
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive,26-35,Large,1,1,3.0
374,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative,18-25,Medium,0,1,2.0
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive,18-25,Small,1,1,3.0

In [26]:
# final data visualization
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285 entries, 0 to 386
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         285 non-null    int64
 1   Gender                      285 non-null    object
 2   Marital Status              285 non-null    object
 3   Occupation                  285 non-null    object
 4   Monthly Income              285 non-null    object
 5   Educational Qualifications  285 non-null    object
 6   Family size                 285 non-null    int64
 7   Customer Type               285 non-null    object
 8   latitude                    285 non-null    float64
 9   longitude                   285 non-null    float64
 10  Pin code                    285 non-null    int64
 11  Output                      285 non-null    object
 12  Feedback                    285 non-null    object
 13  Age_Group                   285 non-null    category
 14  Family_Size_Group           285 non-null    category
 15  Feedback_Flag               285 non-null    int64
 16  Output_Flag                 285 non-null    int64
 17  Education_Level             283 non-null    float64
dtypes: category(2), float64(3), int64(5), object(8)
memory usage: 38.7+ KB

In [27]:
df.isnull().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
Customer Type                 0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
Age_Group                     0
Family_Size_Group             0
Feedback_Flag                 0
Output_Flag                   0
Education_Level               2
dtype: int64

In [28]:
df.describe()

,Age,Family size,latitude,longitude,Pin code,Feedback_Flag,Output_Flag,Education_Level
count,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,283.000000
mean,24.677193,3.270175,12.973429,77.597593,560037.280702,0.810526,0.761404,2.551237
std,3.040977,1.361178,0.043964,0.053557,30.738306,0.392574,0.426975,0.689349
min,18.000000,1.000000,12.865200,77.484200,560001.000000,0.000000,0.000000,1.000000
25%,23.000000,2.000000,12.943800,77.563500,560010.000000,1.000000,1.000000,2.000000
50%,24.000000,3.000000,12.977000,77.587700,560028.000000,1.000000,1.000000,3.000000
75%,26.000000,4.000000,12.998000,77.622700,560066.000000,1.000000,1.000000,3.000000
max,33.000000,6.000000,13.102000,77.758200,560109.000000,1.000000,1.000000,4.000000

In [29]:
# export clean data
df.to_csv("Food_Clean_Data.csv",index=False)

In [34]:
# import data into mysql
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://root:workloadB+@localhost/Food')

In [35]:
df.to_sql(
    name='food_delivery',
    con=engine,
    if_exists='replace',
    index=False
)

285

In [36]:
df

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Age_Group,Family_Size_Group,Feedback_Flag,Output_Flag,Education_Level
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,18-25,Medium,1,1,3.0
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,18-25,Medium,1,1,2.0
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,18-25,Medium,0,1,3.0
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,18-25,Large,1,1,2.0
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,18-25,Medium,1,1,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive,18-25,Small,1,0,2.0
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive,26-35,Medium,1,1,4.0
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive,26-35,Large,1,1,3.0
374,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative,18-25,Medium,0,1,2.0
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive,18-25,Small,1,1,3.0